spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/library"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "juan"
    password: "!123qweASD"
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
