spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/library"
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "library-user"
    password: "!123qweASD"
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
